In [87]:
import requests as req
from bs4 import BeautifulSoup
import re
import pandas as pd

In [88]:
def scraping():
    url = 'https://instabug.com/blog/mobile-game-publishers/'
    html = requests.get(url).content
    bs = BeautifulSoup(html, 'lxml')
    searching = bs.find_all('h3', class_= '')
    developer_list=[e.text.replace('\n','').replace('  ', '') for e in searching]
    top_developer = pd.DataFrame(developer_list,columns = ['top_developer'],)
    return top_developer

In [100]:
def extraerdatos():
    df = pd.read_csv('./appstore_games.csv', encoding='latin')
    df.columns = df.columns.to_series().apply(lambda x: x.strip())
    df.isnull().sum().sort_values().head()/17007
    df_reducido=df[["Name","User Rating Count","Price","Languages","Primary Genre",'Developer',]]
    return df_reducido

In [101]:
df_reducido= extraerdatos()
top_developer=scraping()
pd.concat([df_reducido, top_developer], axis=0)

,Name,User Rating Count,Price,Languages,Primary Genre,Developer,top_developer
0,Sudoku,3553.0,2.99,"DA, NL, EN, FI, FR, DE, IT, JA, KO, NB, PL, PT...",Games,Mighty Mighty Good Games,NaN
1,Reversi,284.0,1.99,EN,Games,Kiss The Machine,NaN
2,Morocco,8376.0,0.00,EN,Games,Bayou Games,NaN
3,Sudoku (Free),190394.0,0.00,"DA, NL, EN, FI, FR, DE, IT, JA, KO, NB, PL, PT...",Games,Mighty Mighty Good Games,NaN
4,Senet Deluxe,28.0,2.99,"DA, NL, EN, FR, DE, EL, IT, JA, KO, NO, PT, RU...",Games,RoGame Software,NaN
...,...,...,...,...,...,...,...
64,NaN,NaN,NaN,NaN,NaN,NaN,Mail.Ru
65,NaN,NaN,NaN,NaN,NaN,NaN,Kizi
66,NaN,NaN,NaN,NaN,NaN,NaN,Indie Fund
67,NaN,NaN,NaN,NaN,NaN,NaN,Learn more:
68,NaN,NaN,NaN,NaN,NaN,NaN,Related Posts